/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QuestionSection } from './question-section';
 /**
 * 
 *
 * @export
 * @interface AnswerChoiceRequest
 */
export interface AnswerChoiceRequest {

    /**
     * @type {number}
     * @memberof AnswerChoiceRequest
     */
    questionId?: number;

    /**
     * @type {QuestionSection}
     * @memberof AnswerChoiceRequest
     */
    section?: QuestionSection;

    /**
     * @type {string}
     * @memberof AnswerChoiceRequest
     */
    optionLabel?: string;
}
