/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuthLoginResponse
 */
export interface AuthLoginResponse {

    /**
     * @type {string}
     * @memberof AuthLoginResponse
     */
    accessToken?: string | null;

    /**
     * @type {string}
     * @memberof AuthLoginResponse
     */
    refreshToken?: string | null;

    /**
     * @type {number}
     * @memberof AuthLoginResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof AuthLoginResponse
     */
    email?: string | null;

    /**
     * @type {string}
     * @memberof AuthLoginResponse
     */
    fullName?: string | null;

    /**
     * @type {string}
     * @memberof AuthLoginResponse
     */
    role?: string | null;
}
