/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuthRegisterRequest
 */
export interface AuthRegisterRequest {

    /**
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    username: string;

    /**
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    email: string;

    /**
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    password: string;

    /**
     * @type {string}
     * @memberof AuthRegisterRequest
     */
    firmPassword: string;
}
