/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExamQuestionResponse } from './exam-question-response';
 /**
 * 
 *
 * @export
 * @interface ExamResponse
 */
export interface ExamResponse {

    /**
     * @type {number}
     * @memberof ExamResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ExamResponse
     */
    examName?: string | null;

    /**
     * @type {string}
     * @memberof ExamResponse
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof ExamResponse
     */
    totalQuestions?: number;

    /**
     * @type {Array<ExamQuestionResponse>}
     * @memberof ExamResponse
     */
    examQuestion?: Array<ExamQuestionResponse> | null;
}
