/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QuestionResponse } from './question-response';
 /**
 * 
 *
 * @export
 * @interface ExamQuestionResponse
 */
export interface ExamQuestionResponse {

    /**
     * @type {number}
     * @memberof ExamQuestionResponse
     */
    id?: number;

    /**
     * @type {number}
     * @memberof ExamQuestionResponse
     */
    examId?: number;

    /**
     * @type {number}
     * @memberof ExamQuestionResponse
     */
    questionId?: number;

    /**
     * @type {QuestionResponse}
     * @memberof ExamQuestionResponse
     */
    question?: QuestionResponse;
}
