/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExamQuestion } from './exam-question';
 /**
 * 
 *
 * @export
 * @interface Exam
 */
export interface Exam {

    /**
     * @type {number}
     * @memberof Exam
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Exam
     */
    examName: string;

    /**
     * @type {string}
     * @memberof Exam
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof Exam
     */
    totalQuestions: number;

    /**
     * @type {Array<ExamQuestion>}
     * @memberof Exam
     */
    examQuestion?: Array<ExamQuestion> | null;
}
