/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Exam } from './exam';
import { Question } from './question';
 /**
 * 
 *
 * @export
 * @interface ExamQuestion
 */
export interface ExamQuestion {

    /**
     * @type {number}
     * @memberof ExamQuestion
     */
    id?: number;

    /**
     * @type {number}
     * @memberof ExamQuestion
     */
    examId: number;

    /**
     * @type {Exam}
     * @memberof ExamQuestion
     */
    exam?: Exam;

    /**
     * @type {number}
     * @memberof ExamQuestion
     */
    questionId: number;

    /**
     * @type {Question}
     * @memberof ExamQuestion
     */
    question: Question;

    /**
     * @type {number}
     * @memberof ExamQuestion
     */
    questionOrder: number;
}
