/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FlashcardSet } from './flashcard-set';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface FlashcardFolder
 */
export interface FlashcardFolder {

    /**
     * @type {number}
     * @memberof FlashcardFolder
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FlashcardFolder
     */
    folderName: string;

    /**
     * @type {number}
     * @memberof FlashcardFolder
     */
    userId?: number;

    /**
     * @type {User}
     * @memberof FlashcardFolder
     */
    user?: User;

    /**
     * @type {Date}
     * @memberof FlashcardFolder
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof FlashcardFolder
     */
    updatedNameAt?: Date;

    /**
     * @type {Array<FlashcardSet>}
     * @memberof FlashcardFolder
     */
    flashcardSets?: Array<FlashcardSet> | null;
}
