/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FlashcardResponse } from './flashcard-response';
 /**
 * 
 *
 * @export
 * @interface FlashcardSetDetailResponse
 */
export interface FlashcardSetDetailResponse {

    /**
     * @type {number}
     * @memberof FlashcardSetDetailResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FlashcardSetDetailResponse
     */
    setName?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardSetDetailResponse
     */
    description?: string | null;

    /**
     * @type {boolean}
     * @memberof FlashcardSetDetailResponse
     */
    isPublic?: boolean;

    /**
     * @type {number}
     * @memberof FlashcardSetDetailResponse
     */
    flashcardFolderId?: number;

    /**
     * @type {number}
     * @memberof FlashcardSetDetailResponse
     */
    userId?: number;

    /**
     * @type {Date}
     * @memberof FlashcardSetDetailResponse
     */
    createdAt?: Date;

    /**
     * @type {number}
     * @memberof FlashcardSetDetailResponse
     */
    totalCards?: number;

    /**
     * @type {Array<FlashcardResponse>}
     * @memberof FlashcardSetDetailResponse
     */
    flashcards?: Array<FlashcardResponse> | null;
}
