/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Flashcard } from './flashcard';
import { FlashcardSet } from './flashcard-set';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface FlashcardTest
 */
export interface FlashcardTest {

    /**
     * @type {number}
     * @memberof FlashcardTest
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FlashcardTest
     */
    testType: string;

    /**
     * @type {number}
     * @memberof FlashcardTest
     */
    score: number;

    /**
     * @type {number}
     * @memberof FlashcardTest
     */
    totalQuestions: number;

    /**
     * @type {number}
     * @memberof FlashcardTest
     */
    userId?: number;

    /**
     * @type {User}
     * @memberof FlashcardTest
     */
    user?: User;

    /**
     * @type {number}
     * @memberof FlashcardTest
     */
    flashcardSetId?: number;

    /**
     * @type {FlashcardSet}
     * @memberof FlashcardTest
     */
    flashcardSet?: FlashcardSet;

    /**
     * @type {Date}
     * @memberof FlashcardTest
     */
    startTime?: Date;

    /**
     * @type {Date}
     * @memberof FlashcardTest
     */
    endTime?: Date;

    /**
     * @type {Array<Flashcard>}
     * @memberof FlashcardTest
     */
    flashcards?: Array<Flashcard> | null;
}
