/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FlashcardResponse
 */
export interface FlashcardResponse {

    /**
     * @type {number}
     * @memberof FlashcardResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FlashcardResponse
     */
    termLanguage?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardResponse
     */
    definitionLanguage?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardResponse
     */
    imageUrl?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardResponse
     */
    audioUrl?: string | null;

    /**
     * @type {boolean}
     * @memberof FlashcardResponse
     */
    isFavorite?: boolean;

    /**
     * @type {boolean}
     * @memberof FlashcardResponse
     */
    isDeleted?: boolean;

    /**
     * @type {number}
     * @memberof FlashcardResponse
     */
    correctCount?: number;

    /**
     * @type {number}
     * @memberof FlashcardResponse
     */
    wrongCount?: number;

    /**
     * @type {Date}
     * @memberof FlashcardResponse
     */
    lastReviewedAt?: Date | null;

    /**
     * @type {Date}
     * @memberof FlashcardResponse
     */
    createdAt?: Date;

    /**
     * @type {number}
     * @memberof FlashcardResponse
     */
    flashcardSetId?: number;

    /**
     * @type {number}
     * @memberof FlashcardResponse
     */
    userId?: number;
}
