/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FlashcardFolderRequest
 */
export interface FlashcardFolderRequest {

    /**
     * @type {string}
     * @memberof FlashcardFolderRequest
     */
    folderName: string;

    /**
     * @type {number}
     * @memberof FlashcardFolderRequest
     */
    userId: number;
}
