/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FlashcardFolderResponse
 */
export interface FlashcardFolderResponse {

    /**
     * @type {number}
     * @memberof FlashcardFolderResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FlashcardFolderResponse
     */
    folderName?: string | null;

    /**
     * @type {number}
     * @memberof FlashcardFolderResponse
     */
    userId?: number;
}
