/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FlashcardFavoritesResponse
 */
export interface FlashcardFavoritesResponse {

    /**
     * @type {number}
     * @memberof FlashcardFavoritesResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FlashcardFavoritesResponse
     */
    termLanguage?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardFavoritesResponse
     */
    definitionLanguage?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardFavoritesResponse
     */
    imageUrl?: string | null;

    /**
     * @type {string}
     * @memberof FlashcardFavoritesResponse
     */
    audioUrl?: string | null;

    /**
     * @type {number}
     * @memberof FlashcardFavoritesResponse
     */
    flashcardSetId?: number;
}
