/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ForumTopic } from './forum-topic';
 /**
 * 
 *
 * @export
 * @interface ForumCategory
 */
export interface ForumCategory {

    /**
     * @type {number}
     * @memberof ForumCategory
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ForumCategory
     */
    name: string;

    /**
     * @type {string}
     * @memberof ForumCategory
     */
    description?: string | null;

    /**
     * @type {Array<ForumTopic>}
     * @memberof ForumCategory
     */
    topics?: Array<ForumTopic> | null;
}
