/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Account } from './account';
import { ForumPost } from './forum-post';
 /**
 * 
 *
 * @export
 * @interface ForumComment
 */
export interface ForumComment {

    /**
     * @type {number}
     * @memberof ForumComment
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ForumComment
     */
    content: string;

    /**
     * @type {Date}
     * @memberof ForumComment
     */
    createAt?: Date;

    /**
     * @type {number}
     * @memberof ForumComment
     */
    postId: number;

    /**
     * @type {ForumPost}
     * @memberof ForumComment
     */
    forumPost?: ForumPost;

    /**
     * @type {number}
     * @memberof ForumComment
     */
    accountId: number;

    /**
     * @type {Account}
     * @memberof ForumComment
     */
    account?: Account;
}
