/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ForumCategory } from './forum-category';
import { ForumPost } from './forum-post';
 /**
 * 
 *
 * @export
 * @interface ForumTopic
 */
export interface ForumTopic {

    /**
     * @type {number}
     * @memberof ForumTopic
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ForumTopic
     */
    title: string;

    /**
     * @type {number}
     * @memberof ForumTopic
     */
    categoryId: number;

    /**
     * @type {ForumCategory}
     * @memberof ForumTopic
     */
    forumCategory?: ForumCategory;

    /**
     * @type {Array<ForumPost>}
     * @memberof ForumTopic
     */
    posts?: Array<ForumPost> | null;
}
