/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Account } from './account';
import { ForumComment } from './forum-comment';
import { ForumEmotion } from './forum-emotion';
import { ForumTopic } from './forum-topic';
 /**
 * 
 *
 * @export
 * @interface ForumPost
 */
export interface ForumPost {

    /**
     * @type {number}
     * @memberof ForumPost
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ForumPost
     */
    title: string;

    /**
     * @type {string}
     * @memberof ForumPost
     */
    content: string;

    /**
     * @type {Date}
     * @memberof ForumPost
     */
    createAt: Date;

    /**
     * @type {number}
     * @memberof ForumPost
     */
    topicId: number;

    /**
     * @type {ForumTopic}
     * @memberof ForumPost
     */
    forumTopic?: ForumTopic;

    /**
     * @type {number}
     * @memberof ForumPost
     */
    accountId: number;

    /**
     * @type {Account}
     * @memberof ForumPost
     */
    account?: Account;

    /**
     * @type {Array<ForumComment>}
     * @memberof ForumPost
     */
    comments?: Array<ForumComment> | null;

    /**
     * @type {Array<ForumEmotion>}
     * @memberof ForumPost
     */
    emotions?: Array<ForumEmotion> | null;
}
