/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QuestionAnswer } from './question-answer';
import { QuestionPart } from './question-part';
import { QuestionSection } from './question-section';
 /**
 * 
 *
 * @export
 * @interface Question
 */
export interface Question {

    /**
     * @type {number}
     * @memberof Question
     */
    id?: number;

    /**
     * @type {QuestionSection}
     * @memberof Question
     */
    section: QuestionSection;

    /**
     * @type {QuestionPart}
     * @memberof Question
     */
    part: QuestionPart;

    /**
     * @type {string}
     * @memberof Question
     */
    content: string;

    /**
     * @type {string}
     * @memberof Question
     */
    imageUrl?: string | null;

    /**
     * @type {string}
     * @memberof Question
     */
    audioUrl?: string | null;

    /**
     * @type {string}
     * @memberof Question
     */
    explanation?: string | null;

    /**
     * @type {boolean}
     * @memberof Question
     */
    isMultipleChoice?: boolean;

    /**
     * @type {Array<QuestionAnswer>}
     * @memberof Question
     */
    questionAnswer?: Array<QuestionAnswer> | null;
}
