/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface QuestionAnswerResponse
 */
export interface QuestionAnswerResponse {

    /**
     * @type {number}
     * @memberof QuestionAnswerResponse
     */
    id?: number;

    /**
     * @type {string}
     * @memberof QuestionAnswerResponse
     */
    optionLabel?: string | null;

    /**
     * @type {string}
     * @memberof QuestionAnswerResponse
     */
    optionText?: string | null;

    /**
     * @type {boolean}
     * @memberof QuestionAnswerResponse
     */
    isAnswer?: boolean;
}
