/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Question } from './question';
 /**
 * 
 *
 * @export
 * @interface QuestionAnswer
 */
export interface QuestionAnswer {

    /**
     * @type {number}
     * @memberof QuestionAnswer
     */
    id?: number;

    /**
     * @type {number}
     * @memberof QuestionAnswer
     */
    questionId: number;

    /**
     * @type {string}
     * @memberof QuestionAnswer
     */
    optionLabel: string;

    /**
     * @type {string}
     * @memberof QuestionAnswer
     */
    optionText: string;

    /**
     * @type {boolean}
     * @memberof QuestionAnswer
     */
    isAnswer: boolean;

    /**
     * @type {Question}
     * @memberof QuestionAnswer
     */
    question?: Question;
}
