/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QuestionAnswerResponse } from './question-answer-response';
import { QuestionPart } from './question-part';
import { QuestionSection } from './question-section';
 /**
 * 
 *
 * @export
 * @interface QuestionResponse
 */
export interface QuestionResponse {

    /**
     * @type {number}
     * @memberof QuestionResponse
     */
    id?: number;

    /**
     * @type {QuestionSection}
     * @memberof QuestionResponse
     */
    section?: QuestionSection;

    /**
     * @type {QuestionPart}
     * @memberof QuestionResponse
     */
    part?: QuestionPart;

    /**
     * @type {string}
     * @memberof QuestionResponse
     */
    content?: string | null;

    /**
     * @type {string}
     * @memberof QuestionResponse
     */
    imageUrl?: string | null;

    /**
     * @type {string}
     * @memberof QuestionResponse
     */
    audioUrl?: string | null;

    /**
     * @type {string}
     * @memberof QuestionResponse
     */
    explanation?: string | null;

    /**
     * @type {boolean}
     * @memberof QuestionResponse
     */
    isMultipleChoice?: boolean;

    /**
     * @type {Array<QuestionAnswerResponse>}
     * @memberof QuestionResponse
     */
    questionAnswers?: Array<QuestionAnswerResponse> | null;
}
