/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserUpdateRequest
 */
export interface UserUpdateRequest {

    /**
     * @type {string}
     * @memberof UserUpdateRequest
     */
    fullName?: string | null;

    /**
     * @type {string}
     * @memberof UserUpdateRequest
     */
    avatarUrl?: string | null;
}
