/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExamBaseResponse } from './exam-base-response';
 /**
 * 
 *
 * @export
 * @interface UserExamFavoriteResponse
 */
export interface UserExamFavoriteResponse {

    /**
     * @type {number}
     * @memberof UserExamFavoriteResponse
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UserExamFavoriteResponse
     */
    userId?: number;

    /**
     * @type {number}
     * @memberof UserExamFavoriteResponse
     */
    examId?: number;

    /**
     * @type {ExamBaseResponse}
     * @memberof UserExamFavoriteResponse
     */
    exam?: ExamBaseResponse;
}
