/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Account } from './account';
import { Flashcard } from './flashcard';
import { FlashcardFolder } from './flashcard-folder';
import { UserExam } from './user-exam';
import { UserExamFavorite } from './user-exam-favorite';
import { UserFlashcardGame } from './user-flashcard-game';
import { UserFlashcardSet } from './user-flashcard-set';
 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {number}
     * @memberof User
     */
    id?: number;

    /**
     * @type {number}
     * @memberof User
     */
    accountId: number;

    /**
     * @type {Account}
     * @memberof User
     */
    account?: Account;

    /**
     * @type {string}
     * @memberof User
     */
    fullName: string;

    /**
     * @type {string}
     * @memberof User
     */
    avatarUrl?: string | null;

    /**
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;

    /**
     * @type {Array<UserExam>}
     * @memberof User
     */
    userExams?: Array<UserExam> | null;

    /**
     * @type {Array<FlashcardFolder>}
     * @memberof User
     */
    flashcardFolders?: Array<FlashcardFolder> | null;

    /**
     * @type {Array<UserFlashcardSet>}
     * @memberof User
     */
    userFlashcardSets?: Array<UserFlashcardSet> | null;

    /**
     * @type {Array<Flashcard>}
     * @memberof User
     */
    flashcards?: Array<Flashcard> | null;

    /**
     * @type {Array<UserFlashcardGame>}
     * @memberof User
     */
    userFlashcardGames?: Array<UserFlashcardGame> | null;

    /**
     * @type {Array<UserExamFavorite>}
     * @memberof User
     */
    userExamFavorites?: Array<UserExamFavorite> | null;
}
