/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Exam } from './exam';
import { ExamStatus } from './exam-status';
import { User } from './user';
import { UserAnswer } from './user-answer';
 /**
 * 
 *
 * @export
 * @interface UserExam
 */
export interface UserExam {

    /**
     * @type {number}
     * @memberof UserExam
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UserExam
     */
    userId: number;

    /**
     * @type {number}
     * @memberof UserExam
     */
    examId: number;

    /**
     * @type {Date}
     * @memberof UserExam
     */
    startTime?: Date;

    /**
     * @type {Date}
     * @memberof UserExam
     */
    endTime?: Date;

    /**
     * @type {number}
     * @memberof UserExam
     */
    durationSeconds?: number;

    /**
     * @type {ExamStatus}
     * @memberof UserExam
     */
    status?: ExamStatus;

    /**
     * @type {number}
     * @memberof UserExam
     */
    scoreReading?: number;

    /**
     * @type {number}
     * @memberof UserExam
     */
    scoreListening?: number;

    /**
     * @type {number}
     * @memberof UserExam
     */
    totalScore?: number;

    /**
     * @type {boolean}
     * @memberof UserExam
     */
    isSubmitted?: boolean;

    /**
     * @type {User}
     * @memberof UserExam
     */
    user?: User;

    /**
     * @type {Exam}
     * @memberof UserExam
     */
    exam?: Exam;

    /**
     * @type {Array<UserAnswer>}
     * @memberof UserExam
     */
    userAnswers?: Array<UserAnswer> | null;
}
