/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Exam } from './exam';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface UserExamFavorite
 */
export interface UserExamFavorite {

    /**
     * @type {number}
     * @memberof UserExamFavorite
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UserExamFavorite
     */
    userId?: number;

    /**
     * @type {User}
     * @memberof UserExamFavorite
     */
    user?: User;

    /**
     * @type {number}
     * @memberof UserExamFavorite
     */
    examId?: number;

    /**
     * @type {Exam}
     * @memberof UserExamFavorite
     */
    exam?: Exam;
}
