/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Question } from './question';
import { QuestionSection } from './question-section';
import { UserExam } from './user-exam';
 /**
 * 
 *
 * @export
 * @interface UserAnswer
 */
export interface UserAnswer {

    /**
     * @type {number}
     * @memberof UserAnswer
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UserAnswer
     */
    userExamId: number;

    /**
     * @type {number}
     * @memberof UserAnswer
     */
    questionId: number;

    /**
     * @type {QuestionSection}
     * @memberof UserAnswer
     */
    section: QuestionSection;

    /**
     * @type {string}
     * @memberof UserAnswer
     */
    userAnswerChoice: string;

    /**
     * @type {UserExam}
     * @memberof UserAnswer
     */
    userExam?: UserExam;

    /**
     * @type {Question}
     * @memberof UserAnswer
     */
    question?: Question;
}
