/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserExamScoreResponse
 */
export interface UserExamScoreResponse {

    /**
     * @type {number}
     * @memberof UserExamScoreResponse
     */
    userId?: number;

    /**
     * @type {number}
     * @memberof UserExamScoreResponse
     */
    userExamId?: number;

    /**
     * @type {number}
     * @memberof UserExamScoreResponse
     */
    scoreListening?: number;

    /**
     * @type {number}
     * @memberof UserExamScoreResponse
     */
    scoreReading?: number;
}
