/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FlashcardSet } from './flashcard-set';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface UserFlashcardGame
 */
export interface UserFlashcardGame {

    /**
     * @type {number}
     * @memberof UserFlashcardGame
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardGame
     */
    userId?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardGame
     */
    setId?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardGame
     */
    totalWord?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardGame
     */
    durationTime?: number;

    /**
     * @type {Date}
     * @memberof UserFlashcardGame
     */
    createdAt?: Date;

    /**
     * @type {User}
     * @memberof UserFlashcardGame
     */
    user?: User;

    /**
     * @type {FlashcardSet}
     * @memberof UserFlashcardGame
     */
    flashcardSet?: FlashcardSet;
}
