/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ExamStatus } from './exam-status';
 /**
 * 
 *
 * @export
 * @interface UserExamBaseRequest
 */
export interface UserExamBaseRequest {

    /**
     * @type {number}
     * @memberof UserExamBaseRequest
     */
    userId?: number;

    /**
     * @type {number}
     * @memberof UserExamBaseRequest
     */
    examId?: number;

    /**
     * @type {ExamStatus}
     * @memberof UserExamBaseRequest
     */
    status?: ExamStatus;
}
