/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FlashcardSet } from './flashcard-set';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface UserFlashcardSet
 */
export interface UserFlashcardSet {

    /**
     * @type {number}
     * @memberof UserFlashcardSet
     */
    id?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardSet
     */
    userId?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardSet
     */
    setId?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardSet
     */
    totalCards?: number;

    /**
     * @type {number}
     * @memberof UserFlashcardSet
     */
    knownCards?: number;

    /**
     * @type {boolean}
     * @memberof UserFlashcardSet
     */
    isCompleted?: boolean;

    /**
     * @type {Date}
     * @memberof UserFlashcardSet
     */
    lastReviewedAt?: Date;

    /**
     * @type {User}
     * @memberof UserFlashcardSet
     */
    user?: User;

    /**
     * @type {FlashcardSet}
     * @memberof UserFlashcardSet
     */
    set?: FlashcardSet;
}
