/* tslint:disable */
/* eslint-disable */
/**
 * Flashduo Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AnswerChoiceRequest } from './answer-choice-request';
 /**
 * 
 *
 * @export
 * @interface UserAnswerRequest
 */
export interface UserAnswerRequest {

    /**
     * @type {number}
     * @memberof UserAnswerRequest
     */
    userId?: number;

    /**
     * @type {Array<AnswerChoiceRequest>}
     * @memberof UserAnswerRequest
     */
    answerChoice?: Array<AnswerChoiceRequest> | null;
}
